## **Collaborative-Filtering Recommender System**

### **Import necessary libraries**

In [11]:
import pandas as pd 
import numpy as np 
from scipy import sparse
from sklearn.metrics.pairwise import cosine_similarity

### **A quick look at the dataset**

In [2]:
test_data = pd.read_csv('testing_data.csv')
train_data = pd.read_csv('training_data.csv')

test_data.head(5)

   UserID  MovieID  Rating
0       1        6       5
1       1       10       3
2       1       12       5
3       1       14       5
4       1       17       3

In [3]:
train_data.head(5)

   UserID  MovieID  Rating
0       1        1       5
1       1        2       3
2       1        3       4
3       1        4       3
4       1        5       3

In [4]:
ratings_train = train_data.values
ratings_test = test_data.values

# indices start from 0
ratings_train[:, :2] -= 1
ratings_test[:, :2] -= 1

In [5]:
n_users = int(np.max(ratings_train[:, 0])) + 1
n_items = int(np.max(ratings_train[:, 1])) + 1
n_users, n_items

(943, 1682)

### **Build the Utility Matrix**

In [8]:
uu_utility_matrix = sparse.coo_matrix((ratings_train[:, 2],
            (ratings_train[:, 1], ratings_train[:, 0])), shape=(n_items, n_users))
uu_utility_matrix = uu_utility_matrix.tocsr()

In [10]:
uu_utility_matrix.toarray()

array([[5, 4, 0, ..., 5, 0, 0],
       [3, 0, 0, ..., 0, 0, 5],
       [4, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)